--------------------------------------------------------
--  文件已创建 - 星期三-十月-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEP
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."DEP" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"TELE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."DEP"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."DEP"."NAME" IS '部门名称';
 
   COMMENT ON COLUMN "ERPUSER"."DEP"."TELE" IS '联系电话';
 
   COMMENT ON TABLE "ERPUSER"."DEP"  IS '部门';
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."EMP" 
   (	"UUID" NUMBER, 
	"USERNAME" VARCHAR2(15 BYTE), 
	"PWD" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(28 BYTE), 
	"GENDER" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"TELE" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"BIRTHDAY" DATE, 
	"DEPUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."EMP"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."USERNAME" IS '登陆名';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."PWD" IS '登陆密码';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."NAME" IS '真实姓名';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."GENDER" IS '性别';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."EMAIL" IS '邮件地址';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."TELE" IS '联系电话';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."ADDRESS" IS '联系地址';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."BIRTHDAY" IS '出生年月日';
 
   COMMENT ON COLUMN "ERPUSER"."EMP"."DEPUUID" IS '部门编号';
 
   COMMENT ON TABLE "ERPUSER"."EMP"  IS '员工';
--------------------------------------------------------
--  DDL for Table EMP_ROLE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."EMP_ROLE" 
   (	"UUID" NUMBER, 
	"EMPUUID" NUMBER, 
	"ROLEUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."EMP_ROLE"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."EMP_ROLE"."EMPUUID" IS '员工编号';
 
   COMMENT ON COLUMN "ERPUSER"."EMP_ROLE"."ROLEUUID" IS '角色编号';
 
   COMMENT ON TABLE "ERPUSER"."EMP_ROLE"  IS '员工角色';
--------------------------------------------------------
--  DDL for Table GOODS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."GOODS" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"ORIGIN" VARCHAR2(30 BYTE), 
	"PRODUCER" VARCHAR2(30 BYTE), 
	"UNIT" VARCHAR2(30 BYTE), 
	"INPRICE" NUMBER(8,2), 
	"OUTPRICE" NUMBER(8,2), 
	"GOODSTYPEUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."GOODS"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."NAME" IS '名称';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."ORIGIN" IS '产地';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."PRODUCER" IS '厂家';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."UNIT" IS '计量单位';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."INPRICE" IS '进货价格';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."OUTPRICE" IS '销售价格';
 
   COMMENT ON COLUMN "ERPUSER"."GOODS"."GOODSTYPEUUID" IS '商品类型';
 
   COMMENT ON TABLE "ERPUSER"."GOODS"  IS '商品';
--------------------------------------------------------
--  DDL for Table GOODSTYPE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."GOODSTYPE" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."GOODSTYPE"."UUID" IS '商品类型编号';
 
   COMMENT ON COLUMN "ERPUSER"."GOODSTYPE"."NAME" IS '商品类型名称';
 
   COMMENT ON TABLE "ERPUSER"."GOODSTYPE"  IS '商品分类';
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."INVENTORY" 
   (	"UUID" NUMBER, 
	"GOODSUUID" NUMBER, 
	"STOREUUID" NUMBER, 
	"NUM" NUMBER, 
	"TYPE" CHAR(1 BYTE), 
	"CREATETIME" DATE, 
	"CHECKTIME" DATE, 
	"CREATER" NUMBER, 
	"CHECKER" NUMBER, 
	"STATE" CHAR(1 BYTE), 
	"REMARK" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."GOODSUUID" IS '商品';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."STOREUUID" IS '仓库';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."NUM" IS '数量';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."TYPE" IS '类型';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."CREATETIME" IS '登记日期';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."CHECKTIME" IS '审核日期';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."CREATER" IS '登记人';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."CHECKER" IS '审核人';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."STATE" IS '状态';
 
   COMMENT ON COLUMN "ERPUSER"."INVENTORY"."REMARK" IS '备注';
 
   COMMENT ON TABLE "ERPUSER"."INVENTORY"  IS '盘盈盘亏';
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."MENU" 
   (	"MENUID" VARCHAR2(20 BYTE), 
	"MENUNAME" VARCHAR2(30 BYTE), 
	"ICON" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(255 BYTE), 
	"PID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."MENU"."MENUID" IS '菜单ID';
 
   COMMENT ON COLUMN "ERPUSER"."MENU"."MENUNAME" IS '菜单名称';
 
   COMMENT ON COLUMN "ERPUSER"."MENU"."ICON" IS '图标';
 
   COMMENT ON COLUMN "ERPUSER"."MENU"."URL" IS 'URL';
 
   COMMENT ON COLUMN "ERPUSER"."MENU"."PID" IS '上级菜单ID';
 
   COMMENT ON TABLE "ERPUSER"."MENU"  IS '菜单';
--------------------------------------------------------
--  DDL for Table ORDERDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ORDERDETAIL" 
   (	"UUID" NUMBER, 
	"GOODSUUID" NUMBER, 
	"GOODSNAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2), 
	"NUM" NUMBER, 
	"MONEY" NUMBER(10,2), 
	"ENDTIME" DATE, 
	"ENDER" NUMBER, 
	"STOREUUID" NUMBER, 
	"STATE" CHAR(1 BYTE), 
	"ORDERSUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."GOODSUUID" IS '商品编号';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."GOODSNAME" IS '商品名称';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."PRICE" IS '价格';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."NUM" IS '数量';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."MONEY" IS '金额';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."ENDTIME" IS '结束日期';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."ENDER" IS '库管员';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."STOREUUID" IS '仓库编号';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."STATE" IS '采购：0=未入库，1=已入库  销售：0=未出库，1=已出库';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERDETAIL"."ORDERSUUID" IS '订单编号';
 
   COMMENT ON TABLE "ERPUSER"."ORDERDETAIL"  IS '订单明细';
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ORDERS" 
   (	"UUID" NUMBER, 
	"CREATETIME" DATE, 
	"CHECKTIME" DATE, 
	"STARTTIME" DATE, 
	"ENDTIME" DATE, 
	"TYPE" CHAR(1 BYTE), 
	"CREATER" NUMBER, 
	"CHECKER" NUMBER, 
	"STARTER" NUMBER, 
	"ENDER" NUMBER, 
	"SUPPLIERUUID" NUMBER, 
	"TOTALMONEY" NUMBER(10,2), 
	"STATE" CHAR(1 BYTE), 
	"WAYBILLSN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."ORDERS"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."CREATETIME" IS '生成日期';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."CHECKTIME" IS '审核日期';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."STARTTIME" IS '确认日期';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."ENDTIME" IS '入库或出库日期';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."TYPE" IS '1:采购 2:销售';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."CREATER" IS '下单员';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."CHECKER" IS '审核员';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."STARTER" IS '采购员';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."ENDER" IS '库管员';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."SUPPLIERUUID" IS '供应商或客户';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."TOTALMONEY" IS '合计金额';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."STATE" IS '采购: 0:未审核 1:已审核, 2:已确认, 3:已入库；销售：0:未出库 1:已出库';
 
   COMMENT ON COLUMN "ERPUSER"."ORDERS"."WAYBILLSN" IS '运单号';
 
   COMMENT ON TABLE "ERPUSER"."ORDERS"  IS '订单';
--------------------------------------------------------
--  DDL for Table RETURNORDERDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."RETURNORDERDETAIL" 
   (	"UUID" NUMBER, 
	"GOODSUUID" NUMBER, 
	"GOODSNAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2), 
	"NUM" NUMBER, 
	"MONEY" NUMBER(10,2), 
	"ENDTIME" DATE, 
	"ENDER" NUMBER, 
	"STOREUUID" NUMBER, 
	"STATE" CHAR(1 BYTE), 
	"ORDERSUUID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."GOODSUUID" IS '商品编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."GOODSNAME" IS '商品名称';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."PRICE" IS '价格';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."NUM" IS '数量';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."MONEY" IS '金额';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."ENDTIME" IS '结束日期';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."ENDER" IS '库管员';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."STOREUUID" IS '仓库编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."STATE" IS '状态';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERDETAIL"."ORDERSUUID" IS '退货订单编号';
 
   COMMENT ON TABLE "ERPUSER"."RETURNORDERDETAIL"  IS '退货订单明细';
--------------------------------------------------------
--  DDL for Table RETURNORDERS
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."RETURNORDERS" 
   (	"UUID" NUMBER, 
	"CREATETIME" DATE, 
	"CHECKTIME" DATE, 
	"ENDTIME" DATE, 
	"TYPE" CHAR(1 BYTE), 
	"CREATER" NUMBER, 
	"CHECKER" NUMBER, 
	"ENDER" NUMBER, 
	"SUPPLIERUUID" NUMBER, 
	"TOTALMONEY" NUMBER(10,2), 
	"STATE" CHAR(1 BYTE), 
	"WAYBILLSN" NUMBER, 
	"ORDERSUUID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."CREATETIME" IS '生成日期';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."CHECKTIME" IS '检查日期';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."ENDTIME" IS '结束日期';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."TYPE" IS '订单类型';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."CREATER" IS '下单员';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."CHECKER" IS '审核员工编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."ENDER" IS '库管员';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."SUPPLIERUUID" IS '供应商及客户编号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."TOTALMONEY" IS '合计金额';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."STATE" IS '订单状态';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."WAYBILLSN" IS '运单号';
 
   COMMENT ON COLUMN "ERPUSER"."RETURNORDERS"."ORDERSUUID" IS '原订单编号';
 
   COMMENT ON TABLE "ERPUSER"."RETURNORDERS"  IS '退货订单';
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ROLE" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."ROLE"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."ROLE"."NAME" IS '名称';
 
   COMMENT ON TABLE "ERPUSER"."ROLE"  IS '角色';
--------------------------------------------------------
--  DDL for Table ROLE_MENU
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."ROLE_MENU" 
   (	"UUID" NUMBER, 
	"ROLEUUID" NUMBER, 
	"MENUUUID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."ROLE_MENU"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."ROLE_MENU"."ROLEUUID" IS '角色编号';
 
   COMMENT ON COLUMN "ERPUSER"."ROLE_MENU"."MENUUUID" IS '菜单编号';
 
   COMMENT ON TABLE "ERPUSER"."ROLE_MENU"  IS '角色菜单';
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STORE" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"EMPUUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."STORE"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."STORE"."NAME" IS '名称';
 
   COMMENT ON COLUMN "ERPUSER"."STORE"."EMPUUID" IS '员工编号';
 
   COMMENT ON TABLE "ERPUSER"."STORE"  IS '仓库';
--------------------------------------------------------
--  DDL for Table STOREDETAIL
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STOREDETAIL" 
   (	"UUID" NUMBER, 
	"STOREUUID" NUMBER, 
	"GOODSUUID" NUMBER, 
	"NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."STOREDETAIL"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREDETAIL"."STOREUUID" IS '仓库编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREDETAIL"."GOODSUUID" IS '商品编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREDETAIL"."NUM" IS '数量';
 
   COMMENT ON TABLE "ERPUSER"."STOREDETAIL"  IS '仓库库存';
--------------------------------------------------------
--  DDL for Table STOREOPER
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."STOREOPER" 
   (	"UUID" NUMBER, 
	"EMPUUID" NUMBER, 
	"OPERTIME" DATE, 
	"STOREUUID" NUMBER, 
	"GOODSUUID" NUMBER, 
	"NUM" NUMBER, 
	"TYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."EMPUUID" IS '操作员工编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."OPERTIME" IS '操作日期';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."STOREUUID" IS '仓库编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."GOODSUUID" IS '商品编号';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."NUM" IS '数量';
 
   COMMENT ON COLUMN "ERPUSER"."STOREOPER"."TYPE" IS '1：入库 2：出库';
 
   COMMENT ON TABLE "ERPUSER"."STOREOPER"  IS '仓库操作记录';
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "ERPUSER"."SUPPLIER" 
   (	"UUID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CONTACT" VARCHAR2(30 BYTE), 
	"TELE" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
 

   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."UUID" IS '编号';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."NAME" IS '名称';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."ADDRESS" IS '联系地址';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."CONTACT" IS '联系人';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."TELE" IS '联系电话';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."EMAIL" IS '邮件地址';
 
   COMMENT ON COLUMN "ERPUSER"."SUPPLIER"."TYPE" IS '1：供应商 2：客户';
 
   COMMENT ON TABLE "ERPUSER"."SUPPLIER"  IS '供应商';
REM INSERTING into ERPUSER.DEP
SET DEFINE OFF;
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (1,'管理员组','000000');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (2,'总裁办','111111');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (3,'采购部','222222');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (4,'销售部','333333');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (5,'公关部','444444');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (6,'行政部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (7,'人事部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (8,'运输部','444444');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (9,'党办','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (10,'工会','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (11,'仓储部','55555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (12,'客服部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (13,'财务部','555555');
Insert into ERPUSER.DEP (UUID,NAME,TELE) values (14,'运营部','555555');
REM INSERTING into ERPUSER.EMP
SET DEFINE OFF;
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (8,'test','085de60f32b004402326e5ee425a6167','拉拉',0,'765785416@qq.com','13114763792','中国广西玉林广场东路',to_date('09-10月-18','DD-MON-RR'),11);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (1,'admin','3ef7164d1f6167cb9f2658c07d3c2f0a','超级管理员',1,'admin@itcast.cn','12345678','建材城西路中腾商务大厦',to_date('01-10月-49','DD-MON-RR'),1);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (2,'sunwukong','02d23c6b8849d0357180807e320fdcb4','孙悟空',1,'swk@itcast.cn','12345678','花果山水帘洞11-2',to_date('01-10月-49','DD-MON-RR'),2);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (3,'tangseng','06216ce1d3d821a93545a33383ad46da','唐僧',1,'ts@itcast.cn','12345678','东土大唐小区90-14',to_date('01-10月-49','DD-MON-RR'),2);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (4,'zhubajie','32bc044e8753478e3cd26898f91e2828','猪八戒',1,'zbj@itcast.cn','12345678','高老庄生态园2-3',to_date('01-10月-49','DD-MON-RR'),3);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (5,'shaheshang','3d4288da2c1db4bbbc4ebf475304c06d','沙和尚',1,'shs@itcast.cn','12345678','流沙河风景区4-4',to_date('01-10月-49','DD-MON-RR'),3);
Insert into ERPUSER.EMP (UUID,USERNAME,PWD,NAME,GENDER,EMAIL,TELE,ADDRESS,BIRTHDAY,DEPUUID) values (6,'bailongma','8bf7134c1a8b4cbd72be4410de4b0f3a','白龙马',1,'blm@itcast.cn','12345678','西海家园4-9-1',to_date('01-10月-49','DD-MON-RR'),3);
REM INSERTING into ERPUSER.EMP_ROLE
SET DEFINE OFF;
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (1,1,1);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (2,2,2);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (3,3,3);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (4,4,4);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (5,5,5);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (6,6,6);
Insert into ERPUSER.EMP_ROLE (UUID,EMPUUID,ROLEUUID) values (9,8,2);
REM INSERTING into ERPUSER.GOODS
SET DEFINE OFF;
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (1,'水蜜桃','北京','北京水果之乡','斤',2.34,4.23,1);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (2,'大鸭梨','北京','北京水果之乡','斤',1.11,3.55,1);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (3,'猕猴桃','北京','北京水果之乡','斤',6.33,9.02,1);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (4,'甜面酱','北京','七必居','袋',4.11,6.33,2);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (5,'可比克','北京','北京山寨食品有限公司','袋',3.88,6.33,3);
Insert into ERPUSER.GOODS (UUID,NAME,ORIGIN,PRODUCER,UNIT,INPRICE,OUTPRICE,GOODSTYPEUUID) values (6,'好吃点','河北','河北好吃点食品公司','袋',4.22,5.21,3);
REM INSERTING into ERPUSER.GOODSTYPE
SET DEFINE OFF;
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (1,'水果');
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (2,'调味品');
Insert into ERPUSER.GOODSTYPE (UUID,NAME) values (3,'儿童食品');
REM INSERTING into ERPUSER.INVENTORY
SET DEFINE OFF;
REM INSERTING into ERPUSER.MENU
SET DEFINE OFF;
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('103','供应商管理','icon-sys','supplier.html?type=1','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('104','客户管理','icon-sys','supplier.html?type=2','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('502','角色设置','icon-sys','role.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('503','用户角色设置','icon-sys','empRoleSet.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('504','角色权限设置','icon-sys','roleMenuSet.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('600','库存管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('601','库存预警','icon-sys','storealert.html','600');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('602','库存管理','icon-sys','storedetail.html','600');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('0','系统菜单','icon-sys',null,null);
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('100','基础数据','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('101','商品类型','icon-sys','goodstype.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('102','商品','icon-sys','goods.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('105','仓库','icon-sys','store.html','100');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('200','人事管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('201','部门管理','icon-sys','dep.html','200');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('202','员工','icon-sys','emp.html','200');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('300','采购管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('301','采购订单查询','icon-sys','orders.html?oper=orders&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('302','采购订单审核','icon-sys','orders.html?oper=doCheck&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('303','采购订单确认','icon-sys','orders.html?oper=doStart&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('304','采购订单入库','icon-sys','orders.html?oper=doInStore&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('305','我的采购订单','icon-sys','orders.html?oper=myorder&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('400','销售管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('401','销售订单查询','icon-sys','orders.html?oper=orders&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('402','销售订单录入','icon-sys','orders.html?oper=myorders&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('403','销售订单出库','icon-sys','orders.html?oper=doOutStore&type=2','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('500','权限管理','icon-sys',null,'0');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('501','重置密码','icon-sys','pwd.html','500');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('306','采购订单申请','icon-sys','orders.html?oper=myorders&type=1','300');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('404','销售统计报表','icon-sys','report_order.html','400');
Insert into ERPUSER.MENU (MENUID,MENUNAME,ICON,URL,PID) values ('405','销售趋势报表','icon-sys','report_trend.html','400');
REM INSERTING into ERPUSER.ORDERDETAIL
SET DEFINE OFF;
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (8,1,'水蜜桃',2.34,100,234,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',4);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (9,6,'好吃点',4.22,100,422,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',4);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (10,4,'甜面酱',4.11,100,411,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',4);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (11,2,'大鸭梨',1.11,100,111,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',5);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (12,6,'好吃点',4.22,100,422,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',5);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (13,5,'可比克',3.88,100,388,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',5);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (20,3,'猕猴桃',6.33,100,633,to_date('01-10月-18','DD-MON-RR'),1,1,'1',10);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (21,5,'可比克',3.88,100,388,to_date('01-10月-18','DD-MON-RR'),1,1,'1',10);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (6,4,'甜面酱',4.11,100,411,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',3);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (7,6,'好吃点',4.22,100,422,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',3);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (14,1,'水蜜桃',4.23,10,42.3,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',6);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (15,3,'猕猴桃',9.02,10,90.2,to_date('02-10月-18','DD-MON-RR'),1,1,'1',6);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (16,5,'可比克',6.33,100,633,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',7);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (17,6,'好吃点',5.21,100,521,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',7);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (18,4,'甜面酱',6.33,100,633,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',8);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (1,2,'大鸭梨',1.11,100,111,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',1);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (2,1,'水蜜桃',2.34,100,234,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',1);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (3,3,'猕猴桃',6.33,100,633,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',1);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (22,1,'水蜜桃',2.34,100,234,null,null,null,'0',11);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (23,2,'大鸭梨',1.11,100,111,null,null,null,'0',11);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (24,5,'可比克',6.33,90,569.7,to_date('02-10月-18','DD-MON-RR'),1,1,'1',12);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (25,5,'可比克',6.33,10,63.3,to_date('02-10月-18','DD-MON-RR'),1,1,'1',13);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (4,1,'水蜜桃',2.34,100,234,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',2);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (5,2,'大鸭梨',1.11,100,111,to_date('26-9月 -18','DD-MON-RR'),1,1,'1',2);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (19,1,'好吃点',10,20,200,to_date('29-9月 -18','DD-MON-RR'),1,1,'1',9);
Insert into ERPUSER.ORDERDETAIL (UUID,GOODSUUID,GOODSNAME,PRICE,NUM,MONEY,ENDTIME,ENDER,STOREUUID,STATE,ORDERSUUID) values (26,5,'可比克',6.33,100,633,null,null,null,'0',14);
REM INSERTING into ERPUSER.ORDERS
SET DEFINE OFF;
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (4,to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),'1',1,1,1,1,1,1067,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (5,to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),'1',1,1,1,1,2,921,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (10,to_date('01-10月-18','DD-MON-RR'),to_date('01-10月-18','DD-MON-RR'),to_date('01-10月-18','DD-MON-RR'),to_date('01-10月-18','DD-MON-RR'),'1',1,1,1,1,1,1021,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (3,to_date('25-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),'1',1,1,1,1,2,833,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (6,to_date('26-9月 -18','DD-MON-RR'),null,null,to_date('02-10月-18','DD-MON-RR'),'2',1,null,null,1,3,132.5,'1',7);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (7,to_date('26-9月 -18','DD-MON-RR'),null,null,to_date('26-9月 -18','DD-MON-RR'),'2',1,null,null,1,3,1154,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (8,to_date('26-9月 -18','DD-MON-RR'),null,null,to_date('26-9月 -18','DD-MON-RR'),'2',1,null,null,1,3,633,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (13,to_date('02-10月-18','DD-MON-RR'),null,null,to_date('02-10月-18','DD-MON-RR'),'2',1,null,null,1,4,63.3,'1',9);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (11,to_date('02-10月-18','DD-MON-RR'),null,null,null,'1',2,null,null,null,1,345,'0',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (12,to_date('02-10月-18','DD-MON-RR'),null,null,to_date('02-10月-18','DD-MON-RR'),'2',1,null,null,1,4,569.7,'1',8);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (2,to_date('24-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),to_date('26-9月 -18','DD-MON-RR'),'1',1,1,1,1,2,345,'3',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (9,to_date('03-1月 -18','DD-MON-RR'),null,null,to_date('29-9月 -18','DD-MON-RR'),'2',1,1,1,1,2,100,'1',null);
Insert into ERPUSER.ORDERS (UUID,CREATETIME,CHECKTIME,STARTTIME,ENDTIME,TYPE,CREATER,CHECKER,STARTER,ENDER,SUPPLIERUUID,TOTALMONEY,STATE,WAYBILLSN) values (14,to_date('02-10月-18','DD-MON-RR'),null,null,null,'2',1,null,null,null,4,633,'0',null);
REM INSERTING into ERPUSER.RETURNORDERDETAIL
SET DEFINE OFF;
REM INSERTING into ERPUSER.RETURNORDERS
SET DEFINE OFF;
REM INSERTING into ERPUSER.ROLE
SET DEFINE OFF;
Insert into ERPUSER.ROLE (UUID,NAME) values (2,'采购员');
Insert into ERPUSER.ROLE (UUID,NAME) values (3,'销售员');
Insert into ERPUSER.ROLE (UUID,NAME) values (4,'库管员');
Insert into ERPUSER.ROLE (UUID,NAME) values (5,'采购经理');
Insert into ERPUSER.ROLE (UUID,NAME) values (6,'仓库主管');
Insert into ERPUSER.ROLE (UUID,NAME) values (1,'超级管理员');
REM INSERTING into ERPUSER.ROLE_MENU
SET DEFINE OFF;
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (106,6,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (107,6,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (108,6,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (57,1,'100');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (58,1,'101');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (59,1,'102');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (60,1,'103');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (61,1,'104');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (62,1,'105');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (63,1,'200');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (64,1,'201');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (65,1,'202');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (66,1,'300');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (67,1,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (68,1,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (69,1,'303');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (70,1,'304');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (71,1,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (72,1,'306');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (73,1,'400');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (74,1,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (75,1,'402');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (76,1,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (77,1,'404');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (78,1,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (79,1,'500');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (80,1,'501');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (81,1,'502');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (82,1,'503');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (83,1,'504');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (84,1,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (85,1,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (86,1,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (87,2,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (88,2,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (89,2,'306');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (90,3,'400');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (91,3,'401');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (92,3,'402');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (93,3,'403');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (94,3,'404');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (95,3,'405');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (96,4,'600');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (97,4,'601');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (98,4,'602');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (99,5,'300');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (100,5,'301');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (101,5,'302');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (102,5,'303');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (103,5,'304');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (104,5,'305');
Insert into ERPUSER.ROLE_MENU (UUID,ROLEUUID,MENUUUID) values (105,5,'306');
REM INSERTING into ERPUSER.STORE
SET DEFINE OFF;
Insert into ERPUSER.STORE (UUID,NAME,EMPUUID) values (1,'食品',1);
Insert into ERPUSER.STORE (UUID,NAME,EMPUUID) values (2,'零食',2);
REM INSERTING into ERPUSER.STOREDETAIL
SET DEFINE OFF;
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (5,1,5,0);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (2,1,1,170);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (3,1,6,200);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (4,1,4,100);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (1,1,2,500);
Insert into ERPUSER.STOREDETAIL (UUID,STOREUUID,GOODSUUID,NUM) values (6,1,3,90);
REM INSERTING into ERPUSER.STOREOPER
SET DEFINE OFF;
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (9,1,to_date('26-9月 -18','DD-MON-RR'),1,2,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (10,1,to_date('26-9月 -18','DD-MON-RR'),1,6,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (11,1,to_date('26-9月 -18','DD-MON-RR'),1,5,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (12,1,to_date('26-9月 -18','DD-MON-RR'),1,1,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (13,1,to_date('26-9月 -18','DD-MON-RR'),1,2,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (2,1,to_date('26-9月 -18','DD-MON-RR'),1,1,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (3,1,to_date('26-9月 -18','DD-MON-RR'),1,3,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (4,1,to_date('26-9月 -18','DD-MON-RR'),1,1,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (5,1,to_date('26-9月 -18','DD-MON-RR'),1,6,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (6,1,to_date('26-9月 -18','DD-MON-RR'),1,4,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (7,1,to_date('26-9月 -18','DD-MON-RR'),1,4,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (8,1,to_date('26-9月 -18','DD-MON-RR'),1,6,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (14,1,to_date('26-9月 -18','DD-MON-RR'),1,1,10,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (15,1,to_date('26-9月 -18','DD-MON-RR'),1,5,100,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (16,1,to_date('26-9月 -18','DD-MON-RR'),1,6,100,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (17,1,to_date('26-9月 -18','DD-MON-RR'),1,4,100,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (18,1,to_date('29-9月 -18','DD-MON-RR'),1,1,20,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (23,1,to_date('02-10月-18','DD-MON-RR'),1,5,10,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (1,1,to_date('26-9月 -18','DD-MON-RR'),1,2,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (19,1,to_date('01-10月-18','DD-MON-RR'),1,3,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (20,1,to_date('01-10月-18','DD-MON-RR'),1,5,100,'1');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (21,1,to_date('02-10月-18','DD-MON-RR'),1,3,10,'2');
Insert into ERPUSER.STOREOPER (UUID,EMPUUID,OPERTIME,STOREUUID,GOODSUUID,NUM,TYPE) values (22,1,to_date('02-10月-18','DD-MON-RR'),1,5,90,'2');
REM INSERTING into ERPUSER.SUPPLIER
SET DEFINE OFF;
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (1,'京东','北京','刘强东','111111','lqd@jd.com','1');
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (2,'淘宝','杭州','马云','22222','my@tb.com','1');
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (3,'玉林牛巴','玉林玉州区','杨俊思','333333','yangjunsi@qq.com','2');
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (4,'奶茶妹妹','北京亦庄经济开发区','章泽天','44444','zzt@qq.com','2');
Insert into ERPUSER.SUPPLIER (UUID,NAME,ADDRESS,CONTACT,TELE,EMAIL,TYPE) values (5,'拼多多','浙江','黄峥','13100985','hz@qq.com','1');
--------------------------------------------------------
--  DDL for Index PK_DEP
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_DEP" ON "ERPUSER"."DEP" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_EMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_EMP" ON "ERPUSER"."EMP" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005922
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."SYS_C005922" ON "ERPUSER"."EMP_ROLE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_GOODS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_GOODS" ON "ERPUSER"."GOODS" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_GOODSTYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_GOODSTYPE" ON "ERPUSER"."GOODSTYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_INVENTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_INVENTORY" ON "ERPUSER"."INVENTORY" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_MENU
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_MENU" ON "ERPUSER"."MENU" ("MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERDETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_ORDERDETAIL" ON "ERPUSER"."ORDERDETAIL" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_ORDERS" ON "ERPUSER"."ORDERS" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_RETURNORDERDETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_RETURNORDERDETAIL" ON "ERPUSER"."RETURNORDERDETAIL" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_RETURNORDERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_RETURNORDERS" ON "ERPUSER"."RETURNORDERS" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_ROLE" ON "ERPUSER"."ROLE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005942
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."SYS_C005942" ON "ERPUSER"."ROLE_MENU" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_STORE
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_STORE" ON "ERPUSER"."STORE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_STOREDETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_STOREDETAIL" ON "ERPUSER"."STOREDETAIL" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_STOREOPER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_STOREOPER" ON "ERPUSER"."STOREOPER" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  DDL for Index PK_SUPPLIER
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERPUSER"."PK_SUPPLIER" ON "ERPUSER"."SUPPLIER" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS" ;
--------------------------------------------------------
--  Constraints for Table DEP
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."DEP" ADD CONSTRAINT "PK_DEP" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."DEP" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."EMP" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMP_ROLE
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."EMP_ROLE" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "ERPUSER"."EMP_ROLE" ADD CONSTRAINT "SYS_C005922" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOODS
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."GOODS" ADD CONSTRAINT "PK_GOODS" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."GOODS" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOODSTYPE
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."GOODSTYPE" ADD CONSTRAINT "PK_GOODSTYPE" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."GOODSTYPE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."INVENTORY" ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."INVENTORY" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY ("MENUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."MENU" MODIFY ("MENUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERDETAIL
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."ORDERDETAIL" ADD CONSTRAINT "PK_ORDERDETAIL" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."ORDERDETAIL" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."ORDERS" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RETURNORDERDETAIL
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."RETURNORDERDETAIL" ADD CONSTRAINT "PK_RETURNORDERDETAIL" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."RETURNORDERDETAIL" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RETURNORDERS
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."RETURNORDERS" ADD CONSTRAINT "PK_RETURNORDERS" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."RETURNORDERS" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."ROLE" ADD CONSTRAINT "PK_ROLE" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."ROLE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE_MENU
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."ROLE_MENU" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "ERPUSER"."ROLE_MENU" ADD CONSTRAINT "SYS_C005942" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."STORE" ADD CONSTRAINT "PK_STORE" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."STORE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOREDETAIL
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."STOREDETAIL" ADD CONSTRAINT "PK_STOREDETAIL" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."STOREDETAIL" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOREOPER
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."STOREOPER" ADD CONSTRAINT "PK_STOREOPER" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."STOREOPER" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "ERPUSER"."SUPPLIER" ADD CONSTRAINT "PK_SUPPLIER" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ERP_TS"  ENABLE;
 
  ALTER TABLE "ERPUSER"."SUPPLIER" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger EMP_ROLE_INCREASE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ERPUSER"."EMP_ROLE_INCREASE" BEFORE
insert ON EMP_ROLE FOR EACH ROW
begin
select EMP_ROLE_Sequence.nextval into:New.UUID from dual;
end;
/
ALTER TRIGGER "ERPUSER"."EMP_ROLE_INCREASE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLE_MENU_INCREASE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ERPUSER"."ROLE_MENU_INCREASE" BEFORE
insert ON ROLE_MENU FOR EACH ROW
begin
select role_menu_Sequence.nextval into:New.UUID from dual;
end;
/
ALTER TRIGGER "ERPUSER"."ROLE_MENU_INCREASE" ENABLE;
